---
title: "curating"
description: |
  A short description of the post.
base_url: https://www.pipinghotdata.com/
preview: 
twitter:
  site: "@PipingHotData"
  creator: "@PipingHotData"
date: 03-14-2021
author:
  - name: Shannon Pileggi
output:
  distill::distill_article:
    toc: true
    toc_depth: 1
    self_contained: false
draft: true
creative_commons: CC BY
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


working title:

Working description:

# TL; DR

# Signing up

R-Ladies has a [comprehensive guide](https://guide.rladies.org/rocur/about/){target="_blank"} describing why the program exists, procedures and protocols for the week, and 
tips for successful curation. You sign up by [submitting a form](https://docs.google.com/forms/d/e/1FAIpQLSevtboT8TNjz87qe5HZzuBHuY0aNteaZNF5e2xFQXtSeU0c0w/viewform){target="_blank"} - give yourself at least 30 minutes to sign up as part of the
form includes filling out details that complete your [curating profile](https://twitter.com/WeAreRLadies/status/1361139211819180032){target="_blank"}.

# Picking a date

You can view the [schedule](https://docs.google.com/spreadsheets/d/1pmphnR9EinGuAKbVqGzMIt6cWYmHNbeFVzaKJB59JdY/edit#gid=1429703967){target="_blank"} of previous and upcoming curators to identify available dates.  

Being a curator will be time intensive, so be kind to yourself. Choose dates when you will have time to invest and a flexible work schedule. I chose Feb 15-20 
because I hoped by then I should be recovered from a very intense Q4 work cycle;
additionally, Feb 15 (President's Day) was a company holiday.

An additional consideration is to schedule your curation to coincide with dates that align with your interests. For example, are you passionate about Black History Month in February, LGBT Pride Month in June, or Universal Human Rights Month in December? 
If so, take advantage of the `@WeAreRLadies` large platform as an opportunity to inform and educate others on issues that are important to you as they relate to the 
R community.

# Countdown

# Content inspiration

As I approached my curating week, I recalled previous `@WeAreRLadies` that were
memorable for me, as well as drew on my previous experience as an educator.

| Inspiration  | Realization               |
|---------------------|-----------------------|
| Rotating curator Mine Çetinkaya-Rundel ([`@minebocek`](https://twitter.com/minebocek){target="_blank"}) tweets awesome [gifs](https://twitter.com/WeAreRLadies/status/1064704918102163457){target="_blank"}| Gifs for R code demos like [this one](https://twitter.com/WeAreRLadies/status/1361802517735178243){target="_blank"}  |
| Rotating curator Megan Stodel ([`@MeganStodel`](https://twitter.com/MeganStodel){target="_blank"}) tweets a [project](https://twitter.com/WeAreRLadies/status/1313177623128944645){target="_blank"} inspired by curating | An R project to [introduce myself](https://twitter.com/WeAreRLadies/status/1361286341317779456){target="_blank"} as a curator |
|Rotating curator Julia Piaskowski ([`@SeedsAndBreeds`](https://twitter.com/SeedsAndBreeds){target="_blank"}) tweets a great technical thread on [ANOVA](https://twitter.com/WeAreRLadies/status/1223790298024726528){target="_blank"} | A thread on [blogging resources](https://twitter.com/WeAreRLadies/status/1363144545677017089){target="_blank"} |
| Prior experience as an educator | Starting discussion with a [question](https://twitter.com/WeAreRLadies/status/1361332603274612739){target="_blank"} |

In addition, I reflected on some questions to inspire content:

* What am I passionate about lately? ([blogging](https://twitter.com/WeAreRLadies/status/1363144545677017089){target="_blank"})

* What did I have to overcome to be where I am today? ([learning how to ask questions online](https://twitter.com/WeAreRLadies/status/1362370580708790274){target="_blank"})

* What have colleagues or students asked me about? ([what needs updating and when](https://twitter.com/WeAreRLadies/status/1362114431090573315){target="_blank"},
[how to re-code variables](https://twitter.com/WeAreRLadies/status/1362450901445865472){target="_blank"}, [colors](https://twitter.com/WeAreRLadies/status/1363286037846511616){target="_blank"})

* What are some R functions or packages that have helped me recently? ([walrus operator](https://twitter.com/WeAreRLadies/status/1361802517735178243){target="_blank"}, [haven + gtsummary](https://twitter.com/WeAreRLadies/status/1363186751133667330){target="_blank"}, [sortable package](https://twitter.com/WeAreRLadies/status/1361418527870132226){target="_blank"})



# Creating content

# Polls

# First and last tweets

# TweetDeck

# Reflection

# Acknowledgements

