---
title: "Modifying the GitHub repo containing my distill website"
description: |
  A short description of the post.
base_url: https://www.pipinghotdata.com/
twitter:
  site: "@PipingHotData"
  creator: "@PipingHotData"
author:
  - name: Shannon Pileggi
    url: {}
date: 2021-12-13
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    self_contained: false
draft: false
creative_commons: CC BY
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# TL; DR

I made two modifications to my distill website and the corresponding GitHub repository:

1.  Added [giscus](https://giscus.app/) commenting to my blog - this was fairly straightforward and completed within 1 to 2 hours.

2.  Added GitHub actions to automatically update the repository's `README` with blog stats - this took several attempts over the course of a few days.

# Giscus commenting

*Straightforward and completed within 1 to 2 hours.*

Updating the commenting mechanism on my website from discus was something I had been meaning to do for a while, but held off on because you never know when a seemingly small change will take you down a rabbit hole.

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

tonight i intended to update my <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> blog from disqus to utterances, but then i found this great post by <a href="https://twitter.com/joel_nitta?ref_src=twsrc%5Etfw">@joel_nitta</a> about ✨giscus✨! thanks, Joel! 👏<br><br>i hope the new giscus gets used - go ahead, pipe up!😉<a href="https://t.co/Wx1j80TKVD">https://t.co/Wx1j80TKVD</a>

</p>

--- Shannon Pileggi (@PipingHotData) <a href="https://twitter.com/PipingHotData/status/1465878389852676107?ref_src=twsrc%5Etfw">December 1, 2021</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
I went for it, and thanks to Joel's awesome post [Enable giscus in Distill](https://www.joelnitta.com/posts/2021-11-24_using-giscus/){target="_blank_"} it was a pretty quick and easy process. 🙌

# Updating the README with GitHub Actions

*Several attempts over the course of a few days.*

After the amazingly quick success of the giscus implementation, I was ready to tackle more! I thought a mini-project on my blog would be a nice entry point to learn GitHub Actions, and I decided to replicate Matt Dray's post [Up-to-date blog stats in your README](https://www.rostrum.blog/2021/04/14/gha-readme/){target="_blank_"}. Between intricacies with both the `README` and the GitHub Action workflow `yaml`, this happened:

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

how is figuring out <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> github actions going, you ask? preeetttty well 👍 <a href="https://t.co/Boj7KvXCAi">pic.twitter.com/Boj7KvXCAi</a>

</p>

--- Shannon Pileggi (@PipingHotData) <a href="https://twitter.com/PipingHotData/status/1466822863286063115?ref_src=twsrc%5Etfw">December 3, 2021</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
I mean, sometimes you can skip reading documentation fully, make a few tweaks to your code, cross your fingers, and hope that everything works. GitHub Actions is probably not one of those things. 😬 Below are a few of the errors I suffered through to get this working; hopefully I can save you some of the pain!

### GitHub Actions

-   [`Error #1`](https://github.com/shannonpileggi/pipinghotdata_distill/runs/4391092220?check_suite_focus=true){target="_blank_"} I needed to add `{distill}` as an installed package in my workflow. 🤷

-   [`Error #2`](https://github.com/shannonpileggi/pipinghotdata_distill/runs/4404442737?check_suite_focus=true){target="_blank_"} I was lazy with my README and workflow and loaded `tidvyerse` instead of the specific packages I needed, which didn't go well. I tried to resolve this via the `pak` route (see next error), which also didn't go well, and ended up trimming back the dependencies to the essential ones.

-   [`Error #10`](https://github.com/shannonpileggi/pipinghotdata_distill/runs/4410903654?check_suite_focus=true){target="_blank_"} I tried a few different things to install packages in the workflow with `pak` instead of `install.packages`. I attempted to use [`r-lib/actions/setup-r-dependencies`](https://github.com/r-lib/actions/tree/master/setup-r-dependencies){target="_blank_"}, and I really should have read the documentation thoroughly. My blog repo is not a package and does not have `DESCRIPTION` file. I tried to add a `DESCRIPTION` file to coerce this, but really, this workflow setup is made for packages. I also attempted to review the source of the workflow and make some tweaks to achieve something similar outside of the package framework, but to no avail. My workflow currently uses `install.packages()`. I could have tried [`r-lib/actions/setup-renv`](https://github.com/r-lib/actions/tree/master/setup-renv){target="_blank_"} instead, but I was tired. There are many errors in my workflow history that correspond to this experimentation.

### README

-   [`Workflow #30`](https://github.com/shannonpileggi/pipinghotdata_distill/runs/4499533757?check_suite_focus=true){target="_blank_"} I thought I would get fancy and make the ggplot graphic interactive through `{ggiraph}` with hover over and click effects. This didn't error out, but it also didn't work, which I should have anticipated, as the rendered file is a `.md` and not a `.Rmd`.

-   [`Workflow #26`](https://github.com/shannonpileggi/pipinghotdata_distill/actions/runs/1562057755){target="_blank_"} I had many workflows that didn't error out, but also did not result in an updated `README`. I actually had a lot of trouble getting the `README` to work. Some things I learned include:

    -   [`usethis::use_readme_rmd()`](https://usethis.r-lib.org/reference/use_readme_rmd.html){target="*blank*"} is designed for use with R packages, and again, didn't work well on my blog repo.

    -   [`devtools::build_rmd()`](https://usethis.r-lib.org/reference/use_readme_rmd.html){target="*blank*"} is designed for use with R packages, and again, didn't work well on my blog repo.

    -   After I ditched these and my README still wasn't rendering correctly, I really, truly thought I was going crazy. I finally found the `rmarkdown::render("README.Rmd", "github_document")` [solution on RStudio Community](https://community.rstudio.com/t/readme-rmd-in-a-bookdown-repo/93191/7?u=shannon.pileggi){target="_blank_"} contributed by Chris Dervieux. I wonder if {distill} has some `YAML` stuff going on that required the `"github_document"` argument.


After much perseverance and persistence, I prevailed with my first GitHub Action. 💪 Perhaps reading the documentation more closely or slowing down to think through things might have worked better for this situation. If you want to have a laugh or or want to feel better about your own struggling efforts, browse through my 34 [commits](https://github.com/shannonpileggi/pipinghotdata_distill/commits/master){target="_blank"} Dec 1 - 12, 2021. Despite the frustration, I remain grateful for these experiences as I learned a lot.

Also, side note moving forward, now that I have a GitHub Action workflow set up on my blog, when I open up my R project I now need to remember to pull before I start writing! 😯

# Acknowledgements

A big thank you to Travis Gerke for talking me through some GitHub Action concepts!